//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterbiteStudios.CodeRomba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinterbiteStudios.CodeRomba.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import .
        /// </summary>
        public static string _UnableToImport {
            get {
                return ResourceManager.GetString("_UnableToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access levels should be ordered by.
        /// </summary>
        public static string AccessLevelsShouldBeOrderedBy {
            get {
                return ResourceManager.GetString("AccessLevelsShouldBeOrderedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access then type.
        /// </summary>
        public static string AccessThenType {
            get {
                return ResourceManager.GetString("AccessThenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add space inside self closing tags.
        /// </summary>
        public static string AddSpaceInsideSelfClosingTags {
            get {
                return ResourceManager.GetString("AddSpaceInsideSelfClosingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add spacing around XML tags.
        /// </summary>
        public static string AddSpacingAroundXMLTags {
            get {
                return ResourceManager.GetString("AddSpacingAroundXMLTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after attributes.
        /// </summary>
        public static string AfterAttributes {
            get {
                return ResourceManager.GetString("AfterAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after opening braces.
        /// </summary>
        public static string AfterOpeningBraces {
            get {
                return ResourceManager.GetString("AfterOpeningBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert threshold.
        /// </summary>
        public static string AlertThreshold {
            get {
                return ResourceManager.GetString("AlertThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align XML param tags.
        /// </summary>
        public static string AlignXMLParamTags {
            get {
                return ResourceManager.GetString("AlignXMLParamTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alphabetical.
        /// </summary>
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetize members of the same group.
        /// </summary>
        public static string AlphabetizeMembersOfTheSameGroup {
            get {
                return ResourceManager.GetString("AlphabetizeMembersOfTheSameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always split all XML tags onto multiple lines.
        /// </summary>
        public static string AlwaysSplitAllXMLTagsOntoMultipleLines {
            get {
                return ResourceManager.GetString("AlwaysSplitAllXMLTagsOntoMultipleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always split summary tags onto multiple lines.
        /// </summary>
        public static string AlwaysSplitSummaryTagsOntoMultipleLines {
            get {
                return ResourceManager.GetString("AlwaysSplitSummaryTagsOntoMultipleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you ready for CodeRomba to clean everything in the solution?.
        /// </summary>
        public static string AreYouReadyForCodeRombaToCleanEverythingInTheSolution {
            get {
                return ResourceManager.GetString("AreYouReadyForCodeRombaToCleanEverythingInTheSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want all .
        /// </summary>
        public static string AreYouSureYouWantAll {
            get {
                return ResourceManager.GetString("AreYouSureYouWantAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at bottom of file.
        /// </summary>
        public static string AtBottomOfFile {
            get {
                return ResourceManager.GetString("AtBottomOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at top of file.
        /// </summary>
        public static string AtTopOfFile {
            get {
                return ResourceManager.GetString("AtTopOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-detect.
        /// </summary>
        public static string AutoDetect {
            get {
                return ResourceManager.GetString("AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically run cleanup on file save.
        /// </summary>
        public static string AutomaticallyRunCleanupOnFileSave {
            get {
                return ResourceManager.GetString("AutomaticallyRunCleanupOnFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically save and close documents opened by cleanup.
        /// </summary>
        public static string AutomaticallySaveAndCloseDocumentsOpenedByCleanup {
            get {
                return ResourceManager.GetString("AutomaticallySaveAndCloseDocumentsOpenedByCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Cleanup On Save - .
        /// </summary>
        public static string AutomaticCleanupOnSave {
            get {
                return ResourceManager.GetString("AutomaticCleanupOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch .
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before closing angle brackets.
        /// </summary>
        public static string BeforeClosingAngleBrackets {
            get {
                return ResourceManager.GetString("BeforeClosingAngleBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before closing braces.
        /// </summary>
        public static string BeforeClosingBraces {
            get {
                return ResourceManager.GetString("BeforeClosingBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before closing tags.
        /// </summary>
        public static string BeforeClosingTags {
            get {
                return ResourceManager.GetString("BeforeClosingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between chained statements.
        /// </summary>
        public static string BetweenChainedStatements {
            get {
                return ResourceManager.GetString("BetweenChainedStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Progress.
        /// </summary>
        public static string BuildProgress {
            get {
                return ResourceManager.GetString("BuildProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build progress window.
        /// </summary>
        public static string BuildProgressWindow {
            get {
                return ResourceManager.GetString("BuildProgressWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache file code models.
        /// </summary>
        public static string CacheFileCodeModels {
            get {
                return ResourceManager.GetString("CacheFileCodeModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling....
        /// </summary>
        public static string Canceling {
            get {
                return ResourceManager.GetString("Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning.
        /// </summary>
        public static string Cleaning {
            get {
                return ResourceManager.GetString("Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning.
        /// </summary>
        public static string Cleaning_n {
            get {
                return ResourceManager.GetString("Cleaning_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Types.
        /// </summary>
        public static string CleaningFileTypesViewModel_FileTypes {
            get {
                return ResourceManager.GetString("CleaningFileTypesViewModel_FileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string CleaningUpdateViewModel_Update {
            get {
                return ResourceManager.GetString("CleaningUpdateViewModel_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup.
        /// </summary>
        public static string Cleanup {
            get {
                return ResourceManager.GetString("Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Active Code.
        /// </summary>
        public static string CleanupActiveCode {
            get {
                return ResourceManager.GetString("CleanupActiveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Active Document.
        /// </summary>
        public static string CleanupActiveDocument {
            get {
                return ResourceManager.GetString("CleanupActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup All Code.
        /// </summary>
        public static string CleanupAllCode {
            get {
                return ResourceManager.GetString("CleanupAllCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup cannot run while debugging..
        /// </summary>
        public static string CleanupCannotRunWhileDebugging {
            get {
                return ResourceManager.GetString("CleanupCannotRunWhileDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Open Code.
        /// </summary>
        public static string CleanupOpenCode {
            get {
                return ResourceManager.GetString("CleanupOpenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Selected Code.
        /// </summary>
        public static string CleanupSelectedCode {
            get {
                return ResourceManager.GetString("CleanupSelectedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Solution Explorer search filtering to find filtered items.
        /// </summary>
        public static string ClearSolutionExplorerSearchFilteringToFindFilteredItems {
            get {
                return ResourceManager.GetString("ClearSolutionExplorerSearchFilteringToFindFilteredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Read-Only.
        /// </summary>
        public static string CloseAllReadOnly {
            get {
                return ResourceManager.GetString("CloseAllReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba cleaned &apos;{0}&apos;..
        /// </summary>
        public static string CodeRombaCleaned0 {
            get {
                return ResourceManager.GetString("CodeRombaCleaned0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Cleanup All Code.
        /// </summary>
        public static string CodeRombaCleanupAllCode {
            get {
                return ResourceManager.GetString("CodeRombaCleanupAllCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Cleanup External File.
        /// </summary>
        public static string CodeRombaCleanupExternalFile {
            get {
                return ResourceManager.GetString("CodeRombaCleanupExternalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Cleanup for &apos;{0}&apos;.
        /// </summary>
        public static string CodeRombaCleanupFor0 {
            get {
                return ResourceManager.GetString("CodeRombaCleanupFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Cleanup Progress.
        /// </summary>
        public static string CodeRombaCleanupProgress {
            get {
                return ResourceManager.GetString("CodeRombaCleanupProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Confirmation for Cleanup All Code.
        /// </summary>
        public static string CodeRombaConfirmationForCleanupAllCode {
            get {
                return ResourceManager.GetString("CodeRombaConfirmationForCleanupAllCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Confirmation for Reset .
        /// </summary>
        public static string CodeRombaConfirmationForReset {
            get {
                return ResourceManager.GetString("CodeRombaConfirmationForReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Confirmation to Save Pending Changes.
        /// </summary>
        public static string CodeRombaConfirmationToSavePendingChanges {
            get {
                return ResourceManager.GetString("CodeRombaConfirmationToSavePendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Delete Items.
        /// </summary>
        public static string CodeRombaDeleteItems {
            get {
                return ResourceManager.GetString("CodeRombaDeleteItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba did not find a non-code comment {0} to reformat..
        /// </summary>
        public static string CodeRombaDidNotFindANonCodeComment0ToReformat {
            get {
                return ResourceManager.GetString("CodeRombaDidNotFindANonCodeComment0ToReformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Export .
        /// </summary>
        public static string CodeRombaExport {
            get {
                return ResourceManager.GetString("CodeRombaExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba failed to load theme &apos;{0}&apos;.  See output window for more details..
        /// </summary>
        public static string CodeRombaFailedToLoadTheme0SeeOutputWindowForMoreDetails {
            get {
                return ResourceManager.GetString("CodeRombaFailedToLoadTheme0SeeOutputWindowForMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba finished formatting the comment..
        /// </summary>
        public static string CodeRombaFinishedFormattingTheComment {
            get {
                return ResourceManager.GetString("CodeRombaFinishedFormattingTheComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba finished formatting the comments {0}..
        /// </summary>
        public static string CodeRombaFinishedFormattingTheComments0 {
            get {
                return ResourceManager.GetString("CodeRombaFinishedFormattingTheComments0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Format Comment.
        /// </summary>
        public static string CodeRombaFormatComment {
            get {
                return ResourceManager.GetString("CodeRombaFormatComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba has successfully exported .
        /// </summary>
        public static string CodeRombaHasSuccessfullyExported {
            get {
                return ResourceManager.GetString("CodeRombaHasSuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba has successfully imported {1} from &apos;{0}&apos;..
        /// </summary>
        public static string CodeRombaHasSuccessfullyImported1From0 {
            get {
                return ResourceManager.GetString("CodeRombaHasSuccessfullyImported1From0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba has successfully reset .
        /// </summary>
        public static string CodeRombaHasSuccessfullyReset {
            get {
                return ResourceManager.GetString("CodeRombaHasSuccessfullyReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Import .
        /// </summary>
        public static string CodeRombaImport {
            get {
                return ResourceManager.GetString("CodeRombaImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Insert Region.
        /// </summary>
        public static string CodeRombaInsertRegion {
            get {
                return ResourceManager.GetString("CodeRombaInsertRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba is cleaning &apos;{0}&apos;....
        /// </summary>
        public static string CodeRombaIsCleaning0 {
            get {
                return ResourceManager.GetString("CodeRombaIsCleaning0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Join.
        /// </summary>
        public static string CodeRombaJoin {
            get {
                return ResourceManager.GetString("CodeRombaJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Move Item Above.
        /// </summary>
        public static string CodeRombaMoveItemAbove {
            get {
                return ResourceManager.GetString("CodeRombaMoveItemAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Move Item Below.
        /// </summary>
        public static string CodeRombaMoveItemBelow {
            get {
                return ResourceManager.GetString("CodeRombaMoveItemBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Move Item Into.
        /// </summary>
        public static string CodeRombaMoveItemInto {
            get {
                return ResourceManager.GetString("CodeRombaMoveItemInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Options.
        /// </summary>
        public static string CodeRombaOptions {
            get {
                return ResourceManager.GetString("CodeRombaOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Remove All Regions.
        /// </summary>
        public static string CodeRombaRemoveAllRegions {
            get {
                return ResourceManager.GetString("CodeRombaRemoveAllRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Remove Region .
        /// </summary>
        public static string CodeRombaRemoveRegion {
            get {
                return ResourceManager.GetString("CodeRombaRemoveRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Remove Regions.
        /// </summary>
        public static string CodeRombaRemoveRegions {
            get {
                return ResourceManager.GetString("CodeRombaRemoveRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Remove Selected Regions.
        /// </summary>
        public static string CodeRombaRemoveSelectedRegions {
            get {
                return ResourceManager.GetString("CodeRombaRemoveSelectedRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba reorganized &apos;{0}&apos;..
        /// </summary>
        public static string CodeRombaReorganized0 {
            get {
                return ResourceManager.GetString("CodeRombaReorganized0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Reorganize for &apos;{0}&apos;.
        /// </summary>
        public static string CodeRombaReorganizeFor0 {
            get {
                return ResourceManager.GetString("CodeRombaReorganizeFor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Reorganize Preprocessor Conditionals.
        /// </summary>
        public static string CodeRombaReorganizePreprocessorConditionals {
            get {
                return ResourceManager.GetString("CodeRombaReorganizePreprocessorConditionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba: Reset .
        /// </summary>
        public static string CodeRombaReset {
            get {
                return ResourceManager.GetString("CodeRombaReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Sort.
        /// </summary>
        public static string CodeRombaSort {
            get {
                return ResourceManager.GetString("CodeRombaSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba Spade.
        /// </summary>
        public static string CodeRombaSpade {
            get {
                return ResourceManager.GetString("CodeRombaSpade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba turned automatic cleanup on save.
        /// </summary>
        public static string CodeRombaTurnedAutomaticCleanupOnSave {
            get {
                return ResourceManager.GetString("CodeRombaTurnedAutomaticCleanupOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba was unable to export .
        /// </summary>
        public static string CodeRombaWasUnableToExport {
            get {
                return ResourceManager.GetString("CodeRombaWasUnableToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba was unable to import .
        /// </summary>
        public static string CodeRombaWasUnableToImport {
            get {
                return ResourceManager.GetString("CodeRombaWasUnableToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba was unable to reset .
        /// </summary>
        public static string CodeRombaWasUnableToReset {
            get {
                return ResourceManager.GetString("CodeRombaWasUnableToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All Solution Explorer.
        /// </summary>
        public static string CollapseAllSolutionExplorer {
            get {
                return ResourceManager.GetString("CollapseAllSolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Selected Solution Explorer.
        /// </summary>
        public static string CollapseSelectedSolutionExplorer {
            get {
                return ResourceManager.GetString("CollapseSelectedSolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse solutions when they are opened.
        /// </summary>
        public static string CollapseSolutionsWhenTheyAreOpened {
            get {
                return ResourceManager.GetString("CollapseSolutionsWhenTheyAreOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsing.
        /// </summary>
        public static string CollapsingViewModel_Collapsing {
            get {
                return ResourceManager.GetString("CollapsingViewModel_Collapsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity.
        /// </summary>
        public static string Complexity {
            get {
                return ResourceManager.GetString("Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config files (*.config)|*.config|All Files (*.*)|*.*.
        /// </summary>
        public static string ConfigFilesConfigConfigAllFiles {
            get {
                return ResourceManager.GetString("ConfigFilesConfigConfigAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains preprocessor conditionals (e.g. #if, #pragma) which reorganization does not currently support.
        ///
        ///Do you want to reorganize anyways (DANGEROUS)?.
        /// </summary>
        public static string ContainsPreprocessorConditionalsEGIfPragmaWhichReorganizationDoesNotCurrentlySupportDoYouWantToReorganizeAnywaysDANGEROUS {
            get {
                return ResourceManager.GetString("ContainsPreprocessorConditionalsEGIfPragmaWhichReorganizationDoesNotCurrentlySupp" +
                        "ortDoYouWantToReorganizeAnywaysDANGEROUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying.
        /// </summary>
        public static string Deploying {
            get {
                return ResourceManager.GetString("Deploying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic.
        /// </summary>
        public static string Diagnostic {
            get {
                return ResourceManager.GetString("Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string Diagnostics {
            get {
                return ResourceManager.GetString("Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics mode.
        /// </summary>
        public static string DiagnosticsMode {
            get {
                return ResourceManager.GetString("DiagnosticsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digging.
        /// </summary>
        public static string Digging {
            get {
                return ResourceManager.GetString("Digging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digging (Spade).
        /// </summary>
        public static string DiggingViewModel_DiggingSpade {
            get {
                return ResourceManager.GetString("DiggingViewModel_DiggingSpade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to perform a partial cleanup?.
        /// </summary>
        public static string DoYouWantToPerformAPartialCleanup {
            get {
                return ResourceManager.GetString("DoYouWantToPerformAPartialCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to reorder, drag over to group, right click to split, double-click to rename.
        /// </summary>
        public static string DragToReorderDragOverToGroupRightClickToSplitDoubleClickToRename {
            get {
                return ResourceManager.GetString("DragToReorderDragOverToGroupRightClickToSplitDoubleClickToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything else (ex: .txt, README).
        /// </summary>
        public static string EverythingElseExTxtREADME {
            get {
                return ResourceManager.GetString("EverythingElseExTxtREADME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: #endregion Methods.
        /// </summary>
        public static string ExEndregionMethods {
            get {
                return ResourceManager.GetString("ExEndregionMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: #region Public Methods, #region Private Methods.
        /// </summary>
        public static string ExRegionPublicMethodsRegionPrivateMethods {
            get {
                return ResourceManager.GetString("ExRegionPublicMethodsRegionPrivateMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra indent for values inside XML comments.
        /// </summary>
        public static string ExtraIndentForValuesInsideXMLComments {
            get {
                return ResourceManager.GetString("ExtraIndentForValuesInsideXMLComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Cleanup On Save.
        /// </summary>
        public static string FeaturesDataTemplate_AutomaticCleanupOnSave {
            get {
                return ResourceManager.GetString("FeaturesDataTemplate_AutomaticCleanupOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features Switch.
        /// </summary>
        public static string FeaturesSwitch {
            get {
                return ResourceManager.GetString("FeaturesSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string FeaturesViewModel_Features {
            get {
                return ResourceManager.GetString("FeaturesViewModel_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Header.
        /// </summary>
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file order.
        /// </summary>
        public static string FileOrder {
            get {
                return ResourceManager.GetString("FileOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding.
        /// </summary>
        public static string FindingViewModel_Finding {
            get {
                return ResourceManager.GetString("FindingViewModel_Finding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find In Solution Explorer.
        /// </summary>
        public static string FindInSolutionExplorer {
            get {
                return ResourceManager.GetString("FindInSolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Comment.
        /// </summary>
        public static string FormatComment {
            get {
                return ResourceManager.GetString("FormatComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string FormattingViewModel_Formatting {
            get {
                return ResourceManager.GetString("FormattingViewModel_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handled Exception.
        /// </summary>
        public static string HandledException {
            get {
                return ResourceManager.GetString("HandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide build progress window when a build stops.
        /// </summary>
        public static string HideBuildProgressWindowWhenABuildStops {
            get {
                return ResourceManager.GetString("HideBuildProgressWindowWhenABuildStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons.
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is only one project in a solution, keep it expanded but still collapse its children.
        /// </summary>
        public static string IfThereIsOnlyOneProjectInASolutionKeepItExpandedButStillCollapseItsChildren {
            get {
                return ResourceManager.GetString("IfThereIsOnlyOneProjectInASolutionKeepItExpandedButStillCollapseItsChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include access level in regions.
        /// </summary>
        public static string IncludeAccessLevelInRegions {
            get {
                return ResourceManager.GetString("IncludeAccessLevelInRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation margin.
        /// </summary>
        public static string IndentationMargin {
            get {
                return ResourceManager.GetString("IndentationMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank line padding after.
        /// </summary>
        public static string InsertBlankLinePaddingAfter {
            get {
                return ResourceManager.GetString("InsertBlankLinePaddingAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank line padding before.
        /// </summary>
        public static string InsertBlankLinePaddingBefore {
            get {
                return ResourceManager.GetString("InsertBlankLinePaddingBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank line padding between.
        /// </summary>
        public static string InsertBlankLinePaddingBetween {
            get {
                return ResourceManager.GetString("InsertBlankLinePaddingBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert blank space before.
        /// </summary>
        public static string InsertBlankSpaceBefore {
            get {
                return ResourceManager.GetString("InsertBlankSpaceBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert end of file trailing new line.
        /// </summary>
        public static string InsertEndOfFileTrailingNewLine {
            get {
                return ResourceManager.GetString("InsertEndOfFileTrailingNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert explicit access modifiers on.
        /// </summary>
        public static string InsertExplicitAccessModifiersOn {
            get {
                return ResourceManager.GetString("InsertExplicitAccessModifiersOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert/keep regions even if they are empty.
        /// </summary>
        public static string InsertKeepRegionsEvenIfTheyAreEmpty {
            get {
                return ResourceManager.GetString("InsertKeepRegionsEvenIfTheyAreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new regions.
        /// </summary>
        public static string InsertNewRegions {
            get {
                return ResourceManager.GetString("InsertNewRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in the selection.
        /// </summary>
        public static string InTheSelection {
            get {
                return ResourceManager.GetString("InTheSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  is not in the solution so some cleanup actions may be unavailable..
        /// </summary>
        public static string IsNotInTheSolutionSoSomeCleanupActionsMayBeUnavailable {
            get {
                return ResourceManager.GetString("IsNotInTheSolutionSoSomeCleanupActionsMayBeUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Lines.
        /// </summary>
        public static string JoinLines {
            get {
                return ResourceManager.GetString("JoinLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep members within regions.
        /// </summary>
        public static string KeepMembersWithinRegions {
            get {
                return ResourceManager.GetString("KeepMembersWithinRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep XML tags together.
        /// </summary>
        public static string KeepXMLTagsTogether {
            get {
                return ResourceManager.GetString("KeepXMLTagsTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load models asynchronously.
        /// </summary>
        public static string LoadModelsAsynchronously {
            get {
                return ResourceManager.GetString("LoadModelsAsynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member type order, grouping and preferred names.
        /// </summary>
        public static string MemberTypeOrderGroupingAndPreferredNames {
            get {
                return ResourceManager.GetString("MemberTypeOrderGroupingAndPreferredNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string Metadata {
            get {
                return ResourceManager.GetString("Metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Complex.
        /// </summary>
        public static string MostComplex {
            get {
                return ResourceManager.GetString("MostComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name only.
        /// </summary>
        public static string NameOnly {
            get {
                return ResourceManager.GetString("NameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        public static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Region.
        /// </summary>
        public static string NewRegion {
            get {
                return ResourceManager.GetString("NewRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for methods.
        /// </summary>
        public static string OnlyForMethods {
            get {
                return ResourceManager.GetString("OnlyForMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to be reset to their defaults?.
        /// </summary>
        public static string OptionsViewModel_OnResetToDefaultsCommandExecuted_ToBeResetToTheirDefaults {
            get {
                return ResourceManager.GetString("OptionsViewModel_OnResetToDefaultsCommandExecuted_ToBeResetToTheirDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other cleaning commands (ex: ReSharper.ReSharper_SilentCleanupCode).
        /// </summary>
        public static string OtherCleaningCommandsExReSharperReSharper_SilentCleanupCode {
            get {
                return ResourceManager.GetString("OtherCleaningCommandsExReSharperReSharper_SilentCleanupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform partial cleanup if file is not in the solution.
        /// </summary>
        public static string PerformPartialCleanupIfFileIsNotInTheSolution {
            get {
                return ResourceManager.GetString("PerformPartialCleanupIfFileIsNotInTheSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perform reorganization when preprocessor conditionals are present.
        /// </summary>
        public static string PerformReorganizationWhenPreprocessorConditionalsArePresent {
            get {
                return ResourceManager.GetString("PerformReorganizationWhenPreprocessorConditionalsArePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place each command on a separate line.
        /// </summary>
        public static string PlaceEachCommandOnASeparateLine {
            get {
                return ResourceManager.GetString("PlaceEachCommandOnASeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place each regular expression on a separate line.
        /// </summary>
        public static string PlaceEachRegularExpressionOnASeparateLine {
            get {
                return ResourceManager.GetString("PlaceEachRegularExpressionOnASeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place each set on a separate line.
        /// </summary>
        public static string PlaceEachSetOnASeparateLine {
            get {
                return ResourceManager.GetString("PlaceEachSetOnASeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place each using statement on a separate line.
        /// </summary>
        public static string PlaceEachUsingStatementOnASeparateLine {
            get {
                return ResourceManager.GetString("PlaceEachUsingStatementOnASeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place explicit interface members at the end of their group.
        /// </summary>
        public static string PlaceExplicitInterfaceMembersAtTheEndOfTheirGroup {
            get {
                return ResourceManager.GetString("PlaceExplicitInterfaceMembersAtTheEndOfTheirGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary ordering should be by.
        /// </summary>
        public static string PrimaryOrderingShouldBeBy {
            get {
                return ResourceManager.GetString("PrimaryOrderingShouldBeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary sort should be by.
        /// </summary>
        public static string PrimarySortShouldBeBy {
            get {
                return ResourceManager.GetString("PrimarySortShouldBeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressing.
        /// </summary>
        public static string ProgressingViewModel_Progressing {
            get {
                return ResourceManager.GetString("ProgressingViewModel_Progressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only.
        /// </summary>
        public static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only Toggle.
        /// </summary>
        public static string ReadOnlyToggle {
            get {
                return ResourceManager.GetString("ReadOnlyToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding.
        /// </summary>
        public static string Rebuilding {
            get {
                return ResourceManager.GetString("Rebuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refreshing....
        /// </summary>
        public static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions that match path names to exclude  (ex: \.resx$ or \\lib\\ ).
        /// </summary>
        public static string RegularExpressionsThatMatchPathNamesToExcludeExResxOrLib {
            get {
                return ResourceManager.GetString("RegularExpressionsThatMatchPathNamesToExcludeExResxOrLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expressions that match path names to include or leave empty to include all files  (ex: \.resx$ or \\lib\\ ).
        /// </summary>
        public static string RegularExpressionsThatMatchPathNamesToIncludeExResxOrLib {
            get {
                return ResourceManager.GetString("RegularExpressionsThatMatchPathNamesToIncludeExResxOrLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove All Regions.
        /// </summary>
        public static string RemoveAllRegions {
            get {
                return ResourceManager.GetString("RemoveAllRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank lines.
        /// </summary>
        public static string RemoveBlankLines {
            get {
                return ResourceManager.GetString("RemoveBlankLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blank spaces.
        /// </summary>
        public static string RemoveBlankSpaces {
            get {
                return ResourceManager.GetString("RemoveBlankSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Current Region.
        /// </summary>
        public static string RemoveCurrentRegion {
            get {
                return ResourceManager.GetString("RemoveCurrentRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove end of file trailing new line.
        /// </summary>
        public static string RemoveEndOfFileTrailingNewLine {
            get {
                return ResourceManager.GetString("RemoveEndOfFileTrailingNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove end of line whitespace.
        /// </summary>
        public static string RemoveEndOfLineWhitespace {
            get {
                return ResourceManager.GetString("RemoveEndOfLineWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove existing regions.
        /// </summary>
        public static string RemoveExistingRegions {
            get {
                return ResourceManager.GetString("RemoveExistingRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove multiple consecutive blank lines.
        /// </summary>
        public static string RemoveMultipleConsecutiveBlankLines {
            get {
                return ResourceManager.GetString("RemoveMultipleConsecutiveBlankLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Region.
        /// </summary>
        public static string RemoveRegion {
            get {
                return ResourceManager.GetString("RemoveRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove regions.
        /// </summary>
        public static string RemoveRegions {
            get {
                return ResourceManager.GetString("RemoveRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove Selected Regions.
        /// </summary>
        public static string RemoveSelectedRegions {
            get {
                return ResourceManager.GetString("RemoveSelectedRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRomba is reorganizing &apos;{0}&apos;....
        /// </summary>
        public static string Reorganize_CodeRombaIsReorganizing0 {
            get {
                return ResourceManager.GetString("Reorganize_CodeRombaIsReorganizing0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorganize Active Code.
        /// </summary>
        public static string ReorganizeActiveCode {
            get {
                return ResourceManager.GetString("ReorganizeActiveCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorganize Active Document.
        /// </summary>
        public static string ReorganizeActiveDocument {
            get {
                return ResourceManager.GetString("ReorganizeActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorganizing.
        /// </summary>
        public static string Reorganizing {
            get {
                return ResourceManager.GetString("Reorganizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string ReorganizingTypesViewModel_Types {
            get {
                return ResourceManager.GetString("ReorganizingTypesViewModel_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Defaults.
        /// </summary>
        public static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run format comments during cleanup.
        /// </summary>
        public static string RunFormatCommentsDuringCleanup {
            get {
                return ResourceManager.GetString("RunFormatCommentsDuringCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run format document.
        /// </summary>
        public static string RunFormatDocument {
            get {
                return ResourceManager.GetString("RunFormatDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run JetBrains ReSharper cleanup.
        /// </summary>
        public static string RunJetBrainsReSharperCleanup {
            get {
                return ResourceManager.GetString("RunJetBrainsReSharperCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run remove and sort using statements.
        /// </summary>
        public static string RunRemoveAndSortUsingStatements {
            get {
                return ResourceManager.GetString("RunRemoveAndSortUsingStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run reorganize at start of cleanup.
        /// </summary>
        public static string RunReorganizeAtStartOfCleanup {
            get {
                return ResourceManager.GetString("RunReorganizeAtStartOfCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Telerik JustCode cleanup.
        /// </summary>
        public static string RunTelerikJustCodeCleanup {
            get {
                return ResourceManager.GetString("RunTelerikJustCodeCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run XAML Styler cleanup.
        /// </summary>
        public static string RunXAMLStylerCleanup {
            get {
                return ResourceManager.GetString("RunXAMLStylerCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search CodeRomba Spade (Ctrl+M, ;).
        /// </summary>
        public static string SearchCodeRombaSpadeCtrlM {
            get {
                return ResourceManager.GetString("SearchCodeRombaSpadeCtrlM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .  See output window for more details..
        /// </summary>
        public static string SeeOutputWindowForMoreDetails {
            get {
                return ResourceManager.GetString("SeeOutputWindowForMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sub-category to set options..
        /// </summary>
        public static string SelectASubCategoryToSetOptions {
            get {
                return ResourceManager.GetString("SelectASubCategoryToSetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets of related file extensions  (ex: .cpp .h ).
        /// </summary>
        public static string SetsOfRelatedFileExtensionsExCppH {
            get {
                return ResourceManager.GetString("SetsOfRelatedFileExtensionsExCppH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string SettingCleanupOnSaveCommand_OFF {
            get {
                return ResourceManager.GetString("SettingCleanupOnSaveCommand_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string SettingCleanupOnSaveCommand_ON {
            get {
                return ResourceManager.GetString("SettingCleanupOnSaveCommand_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show build progress on Visual Studio icon in Windows taskbar.
        /// </summary>
        public static string ShowBuildProgressOnVisualStudioIconInWindowsTaskbar {
            get {
                return ResourceManager.GetString("ShowBuildProgressOnVisualStudioIconInWindowsTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show build progress window when a build starts.
        /// </summary>
        public static string ShowBuildProgressWindowWhenABuildStarts {
            get {
                return ResourceManager.GetString("ShowBuildProgressWindowWhenABuildStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item complexity (McCabe).
        /// </summary>
        public static string ShowItemComplexityMcCabe {
            get {
                return ResourceManager.GetString("ShowItemComplexityMcCabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item metadata.
        /// </summary>
        public static string ShowItemMetadata {
            get {
                return ResourceManager.GetString("ShowItemMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show item types.
        /// </summary>
        public static string ShowItemTypes {
            get {
                return ResourceManager.GetString("ShowItemTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show method parameters.
        /// </summary>
        public static string ShowMethodParameters {
            get {
                return ResourceManager.GetString("ShowMethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show start page when a solution is closed.
        /// </summary>
        public static string ShowStartPageWhenASolutionIsClosed {
            get {
                return ResourceManager.GetString("ShowStartPageWhenASolutionIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip during automatic cleanup on save.
        /// </summary>
        public static string SkipDuringAutomaticCleanupOnSave {
            get {
                return ResourceManager.GetString("SkipDuringAutomaticCleanupOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip wrapping on the last word.
        /// </summary>
        public static string SkipWrappingOnTheLastWord {
            get {
                return ResourceManager.GetString("SkipWrappingOnTheLastWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string SolutionExplorer {
            get {
                return ResourceManager.GetString("SolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution-Specific Settings.
        /// </summary>
        public static string SolutionSpecificSettings {
            get {
                return ResourceManager.GetString("SolutionSpecificSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Lines.
        /// </summary>
        public static string SortLines {
            get {
                return ResourceManager.GetString("SortLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spade.
        /// </summary>
        public static string Spade {
            get {
                return ResourceManager.GetString("Spade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spade Tool Window.
        /// </summary>
        public static string SpadeToolWindow {
            get {
                return ResourceManager.GetString("SpadeToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Successful.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;witch File.
        /// </summary>
        public static string SWitchFile {
            get {
                return ResourceManager.GetString("SWitchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch File.
        /// </summary>
        public static string SwitchFile_no_alt {
            get {
                return ResourceManager.GetString("SwitchFile_no_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching.
        /// </summary>
        public static string SwitchingViewModel_Switching {
            get {
                return ResourceManager.GetString("SwitchingViewModel_Switching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;witch to .
        /// </summary>
        public static string SWitchTo {
            get {
                return ResourceManager.GetString("SWitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize outlining with the code file.
        /// </summary>
        public static string SynchronizeOutliningWithTheCodeFile {
            get {
                return ResourceManager.GetString("SynchronizeOutliningWithTheCodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T4 generated code.
        /// </summary>
        public static string T4GeneratedCode {
            get {
                return ResourceManager.GetString("T4GeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily open solution folders to find nested items.
        /// </summary>
        public static string TemporarilyOpenSolutionFoldersToFindNestedItems {
            get {
                return ResourceManager.GetString("TemporarilyOpenSolutionFoldersToFindNestedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party.
        /// </summary>
        public static string ThirdPartyViewModel_ThirdParty {
            get {
                return ResourceManager.GetString("ThirdPartyViewModel_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone..
        /// </summary>
        public static string ThisActionCannotBeUndone {
            get {
                return ResourceManager.GetString("ThisActionCannotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to &apos;{0}&apos;..
        /// </summary>
        public static string To0 {
            get {
                return ResourceManager.GetString("To0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Windows.
        /// </summary>
        public static string ToolWindows {
            get {
                return ResourceManager.GetString("ToolWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type then access.
        /// </summary>
        public static string TypeThenAccess {
            get {
                return ResourceManager.GetString("TypeThenAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to export .
        /// </summary>
        public static string UnableToExport {
            get {
                return ResourceManager.GetString("UnableToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reset .
        /// </summary>
        public static string UnableToReset {
            get {
                return ResourceManager.GetString("UnableToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to toggle read only state on .
        /// </summary>
        public static string UnableToToggleReadOnlyStateOn {
            get {
                return ResourceManager.GetString("UnableToToggleReadOnlyStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under the cursor.
        /// </summary>
        public static string UnderTheCursor {
            get {
                return ResourceManager.GetString("UnderTheCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Unsuccessful.
        /// </summary>
        public static string Unsuccessful {
            get {
                return ResourceManager.GetString("Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update accessors to both be single-line or multi-line (SA1504).
        /// </summary>
        public static string UpdateAccessorsToBothBeSingleLineOrMultiLineSA1504 {
            get {
                return ResourceManager.GetString("UpdateAccessorsToBothBeSingleLineOrMultiLineSA1504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update #endregion tags with region name.
        /// </summary>
        public static string UpdateEndregionTagsWithRegionName {
            get {
                return ResourceManager.GetString("UpdateEndregionTagsWithRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update single line methods by placing braces on separate lines (SA1502).
        /// </summary>
        public static string UpdateSingleLineMethodsByPlacingBracesOnSeparateLinesSA1502 {
            get {
                return ResourceManager.GetString("UpdateSingleLineMethodsByPlacingBracesOnSeparateLinesSA1502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use undo transactions.
        /// </summary>
        public static string UseUndoTransactions {
            get {
                return ResourceManager.GetString("UseUndoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using statements to re-insert when removed  (ex: using System; ).
        /// </summary>
        public static string UsingStatementsToReInsertWhenRemovedExUsingSystem {
            get {
                return ResourceManager.GetString("UsingStatementsToReInsertWhenRemovedExUsingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visuals.
        /// </summary>
        public static string Visuals {
            get {
                return ResourceManager.GetString("Visuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning threshold.
        /// </summary>
        public static string WarningThreshold {
            get {
                return ResourceManager.GetString("WarningThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was stopped.
        /// </summary>
        public static string WasStopped {
            get {
                return ResourceManager.GetString("WasStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When navigating center on.
        /// </summary>
        public static string WhenNavigatingCenterOn {
            get {
                return ResourceManager.GetString("WhenNavigatingCenterOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When sorting by type, secondary sort should be by.
        /// </summary>
        public static string WhenSortingByTypeSecondarySortShouldBeBy {
            get {
                return ResourceManager.GetString("WhenSortingByTypeSecondarySortShouldBeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While Cleaning.
        /// </summary>
        public static string WhileCleaning {
            get {
                return ResourceManager.GetString("WhileCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whitespace.
        /// </summary>
        public static string Whitespace {
            get {
                return ResourceManager.GetString("Whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whole item.
        /// </summary>
        public static string WholeItem {
            get {
                return ResourceManager.GetString("WholeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows taskbar.
        /// </summary>
        public static string WindowsTaskbar {
            get {
                return ResourceManager.GetString("WindowsTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap comments at column.
        /// </summary>
        public static string WrapCommentsAtColumn {
            get {
                return ResourceManager.GetString("WrapCommentsAtColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have pending changes.  Do you want to save them before continuing?.
        /// </summary>
        public static string YouHavePendingChangesDoYouWantToSaveThemBeforeContinuing {
            get {
                return ResourceManager.GetString("YouHavePendingChangesDoYouWantToSaveThemBeforeContinuing", resourceCulture);
            }
        }
    }
}
